### ISSUE TITLE
sail: `/app/cgol/play/hoon` completion

### ISSUE THREAD

**Issue by rabsef-bicrym** [dalten-collective/cgol#7]
# TODO:

- [ ]  I can specify the number of cycles I'd like to perform and hit play
- [ ]  I see my display update and count down with a `n` second timer between phases
- [ ]  I have a cancel button I can press
- [ ]  URL parameter `play` with a value of `on` causes us to continue playing
- [ ]  A counter counts down how many remaining frames I have
- [ ]  A step counter counts up for my game
- [ ]  I can click `save` and save the state of my game to `state`
- [X]  I can click `make` to make a new board
- [X]  I can click the checkboxes and interact, the reading of which changes to the state of my board
- [ ]  I can click `load` and I'm taken to `/game/hoon`
